# Preparation

Preparation biasa dilakukan untuk mempersiapkan data sebelum masuk dalam tahap pemodelan. <br>
Berikut adalah tahapan yang akan dilalui pada data `SC_HW1_bank_data.csv` sebelum tahap pemodelan :
1. Import Library
2. Input Dataset
3. Preprocessing
4. Train-Test Split

## Import Library

In [ ]:
import pandas as pd
import numpy as np

## Input Dataset

In [ ]:
#Membaca data dan memasukkannya ke dalam bentuk Pandas Dataframe
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')

In [ ]:
#Jalankan code untuk mengecek nama kolom yang tersedia
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
#Hilangkan kolom yang dirasa tidak relevan dengan model (contoh: ID). None dapat diisi dengan nama-nama kolom yang akan digunakan.
#Contoh df = df[['X1','X2', 'Y']].copy()

#START CODE
df = df[['Geography', 'Gender', 'Age', 'Balance', 'Exited']].copy()


## Preprocessing

In [ ]:
#Lakukan One-Hot Encoder untuk data categorical, dengan fungsi pandas get_dummies

#START CODE
df = pd.get_dummies(df, columns=['Geography', 'Gender', 'Age', 'Balance', 'Exited'], drop_first=True)

In [ ]:
#Pisahkan mana X (feature) dengan Y,
#Y adalah kolom "Exited"

#START CODE
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [ ]:
#Lakukan Scaler dan/atau Noermalisasi jika diperlukan
from sklearn.preprocessing import MinMaxScaler

#START CODE
scaler = MinMaxScaler()
X_transform = scaler.fit_transform(X)

In [ ]:
#Ini digunakan jika dilakukan scaler/Normalisas. Jika tidak, code ini bisa dilewat dan diganti dengan code yang ada di dalam komen
X_transform = pd.DataFrame(X_transform, columns = X.columns)
#X_transform = X.copy()

## Train-Test Split

In [ ]:
#Split menjadi train dan test dengan test_size 25%
#Tidak perlu mengubah code ini

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_transform,y,test_size = 0.25,random_state = 123)

# Modeling

## Model1

### Soal :
Jelaskan secara Singkat Model pertama yang digunakan!

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


#START CODE
from sklearn.linear_model import LogisticRegression #memanggil libary scikit-learn untuk mengimpor kelas LogisticRegression
model1 = LogisticRegression() #membuat instance dari class Logisticregression yang kemudian disimpan dalam variabel model1
params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]} #sebagai daftar hyperparameter yang akan diuji dalam proses pencarian grid dimana t adalah toleransi untuk kriteria berhenti dan c sebagai kekuatan regularisasi.
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV #untuk mengimpor kelas GridSearchCV dari library scikit-learn
grid = GridSearchCV( #membuat instance dari kelas GridSearchCV dan menyimpannya di variabel grid.
             estimator= model1, #model1 yang dioptimalkan
             param_grid= params, #daftar parameter yang diuji
             scoring = 'accuracy', #untuk memilih model terbaik dengan melakukan accuracy
             n_jobs = 10, # core cpu yang digunakan
             cv = 3 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid.fit(X_train,y_train) #melatih model
grid.best_params_ #mengembalikan parameter terbaik yang ditemukan oleh pencarian grid

{'C': 1.5, 'tol': 0.01}

Model ke-1 menggunakan Logistic Regression dari librray scikit-learn dimana Regresi logistik adalah suatu metode yang digunakan untuk memodelkan hubungan antara variabel dependen biner dengan 1 atau lebih independen.

In [ ]:
#lakukan evaluasi dengan beberapa maetric di bawah ini
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1983
           1       0.63      0.24      0.34       517

    accuracy                           0.81      2500
   macro avg       0.73      0.60      0.62      2500
weighted avg       0.79      0.81      0.78      2500


[[1910   73]
 [ 395  122]]

0.8128


## Model2
### Soal :
Jelaskan secara Singkat Model ke-2 yang digunakan!

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


#START CODE
from sklearn.neighbors import KNeighborsClassifier #memanggil libary scikit-learn untuk mengimpor kelas K-Nearest Neighbor (KNN) Classifier
model2 = KNeighborsClassifier() #membuat instance dari class K-Nearest Neighbor (KNN) Classifier yang kemudian disimpan dalam variabel model2
params = { "n_neighbors": [3, 5, 7], "weights": ['uniform', 'distance']} ##sebagai daftar hyperparameter yang akan diuji dalam proses pencarian grid untuk menentukan parameter terbaik untuk model KNN dimana n-neighbors adalah jumlah tetangga terdekat yang dipertimbangkan dalam klasifikasi dan 'weights' adalah metode untuk menentukan bobot pada tetangga terdekat
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV  #untuk mengimpor kelas GridSearchCV dari library scikit-learn
grid = GridSearchCV( #membuat instance dari kelas GridSearchCV dan menyimpannya di variabel grid.
             estimator= model2, #model1 yang dioptimalkan
             param_grid= params, #daftar parameter yang diuji
             scoring = 'accuracy', #untuk memilih model terbaik dengan melakukan accuracy
             n_jobs = 10, # core cpu yang digunakan
             cv = 3 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid.fit(X_train,y_train) #melatih model
grid.best_params_ #mengembalikan parameter terbaik yang ditemukan oleh pencarian grid

{'n_neighbors': 7, 'weights': 'uniform'}

Model ke-2 menggunakan K-Nearest Neightbor (KNN) Classifier dari library scikit-learn dimana KNN adalah suatu metode machine learning yang digunakan untuk klasifikasi berdasarkan kedekatan (jarak) antara data poin dalam fitur.

In [ ]:
#lakukan evaluasi
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88      1983
           1       0.52      0.22      0.31       517

    accuracy                           0.80      2500
   macro avg       0.67      0.58      0.59      2500
weighted avg       0.76      0.80      0.76      2500


[[1880  103]
 [ 404  113]]

0.7972


## Model3
### Soal :
Jelaskan secara Singkat Model ke-3 yang digunakan!

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


#START CODE
from sklearn.tree import DecisionTreeClassifier #memanggil libary scikit-learn untuk mengimpor kelas Decision Tree Classifier
model3 = DecisionTreeClassifier() #membuat instance dari class Decision Tree Classifier yang kemudian disimpan dalam variabel model1
params = { "max_depth": [None, 5, 10], "min_samples_split": [2, 5, 10]} #sebagai daftar hyperparameter yang akan diuji dalam proses pencarian grid untuk menentukan parameter terbaik untuk model Decision Tree. dimanaa 'max-depth' sebagai kedalaman maksimum dari pohon(None ini berarti tanpa batas kedalaman), dan 'min_samples_split' adalah jumlah minimun sample yang diperlukan untuk membagi node.
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV #untuk mengimpor kelas GridSearchCV dari library scikit-learn
grid = GridSearchCV( #membuat instance dari kelas GridSearchCV dan menyimpannya di variabel grid.
             estimator= model3, #model1 yang dioptimalkan
             param_grid= params, #daftar parameter yang diuji
             scoring = 'accuracy', #untuk memilih model terbaik dengan melakukan accuracy
             n_jobs = 10, # core cpu yang digunakan
             cv = 3 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid.fit(X_train,y_train) #melatih model
grid.best_params_ #mengembalikan parameter terbaik yang ditemukan oleh pencarian grid

{'max_depth': None, 'min_samples_split': 10}

Model ke-2 menggunakan Decision Tree Classifier dari library scikit-learn dimana Decision Tree adalah metode machine leraning yang membangun model prediksi dalam bentuk pohon struktur keputusan.

In [ ]:
#lakukan evaluasi
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.95      0.89      1983
           1       0.58      0.28      0.38       517

    accuracy                           0.81      2500
   macro avg       0.71      0.61      0.63      2500
weighted avg       0.78      0.81      0.78      2500


[[1878  105]
 [ 373  144]]

0.8088


## Tarik Kesimpulan Model Mana yang terbaik beserta alasannya

In [ ]:
Model yang terbaik adalah model ketiga karena waktu komputasi yang dibutuhkan lebih sedikit dibangding model 1 dan model 2. Kemudian diantara 3 model machine learning yang digunakan model ke-3 memiliki nilai accuracy yang paling
mendekati 1 yang berarti model ke-3 semakin akurat dalam memprediksi data untuk pelatihan dan pengujian.